import React from "react";
import { BookOpen, Brain, Zap, Layers, BarChart3, ShieldCheck } from "lucide-react";
import { FineLineHeader } from "./ui/FineLineHeader";

export const ReportGlossary: React.FC = () => {
  return (
    <div className="max-w-[1200px] mx-auto space-y-16 py-8">
      {/* Header Banner */}
      <div className="border-b border-white/10 pb-10">
        <FineLineHeader
          as="h1"
          variant="horizon"
          tag="[REFERENCE METHODOLOGY // SLA SPEC]"
          secondaryTag="NEUROVIRAL TRIBE v2"
          className="font-display font-extrabold text-4xl md:text-5xl text-white tracking-tight uppercase"
          lineColor="rgba(0, 245, 212, 0.45)"
        >
          Methodology & SLA Metrics
        </FineLineHeader>
        <p className="text-sm md:text-base text-neutral-400 font-mono max-w-3xl mt-4 leading-relaxed">
          [METRIC_CODEX] A transparent breakdown of the proprietary metrics generated by the NeuroViral TRIBE v2 model, utilized for robust media monitoring, campaign evaluation, and creator performance reports.
        </p>
      </div>

      {/* Block 1: Core Composite Metrics */}
      <div className="border-t border-white/10 pt-8 grid grid-cols-1 md:grid-cols-12 gap-8">
        <div className="md:col-span-4">
          <FineLineHeader
            as="h3"
            variant="underline"
            tag="[01 // PREDICTIVE METRICS]"
            className="font-display text-2xl font-bold text-white uppercase"
            lineColor="rgba(0, 245, 212, 0.4)"
          >
            Composite Metrics
          </FineLineHeader>
          <p className="font-mono text-xs text-neutral-400 mt-2 uppercase tracking-wider font-semibold">Behavioral Prediction</p>
        </div>
        <div className="md:col-span-8 space-y-8">
          <div className="bg-[#F4F4F4] p-6 rounded-sm border border-[#E5E5E5]">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-xl font-bold text-[#111111]">Virality Index</h4>
              <span className="font-mono text-xs font-semibold bg-[#111111] text-white px-2.5 py-1 rounded-sm">
                0 - 100 Composite
              </span>
            </div>
            <p className="text-[#333333] leading-relaxed font-normal text-sm mt-3">
              The ultimate composite metric indicating the probability of exponential algorithmic distribution. Calculated by mapping aggregate neural activation density against historical social media monitoring data. Scores &gt;85 warrant immediate amplification via paid media channels.
            </p>
          </div>

          <div className="bg-[#F4F4F4] p-6 rounded-sm border border-[#E5E5E5]">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-xl font-bold text-[#111111]">3-Second Hook Score</h4>
              <span className="font-mono text-xs font-semibold bg-[#111111] text-white px-2.5 py-1 rounded-sm">
                SLA Target: &gt;78%
              </span>
            </div>
            <p className="text-[#333333] leading-relaxed font-normal text-sm mt-3">
              Quantifies cognitive salience within the crucial first 3 seconds of a creator's video. Relies on visual pattern interrupts and auditory novelty to overcome baseline user inertia. Essential for meeting SLA retention targets.
            </p>
          </div>
        </div>
      </div>

      {/* Block 2: Neural Networks */}
      <div className="border-t border-[#E5E5E5] pt-8 grid grid-cols-1 md:grid-cols-12 gap-8">
        <div className="md:col-span-4">
          <h3 className="font-display text-2xl font-bold text-[#111111]">2. Neural Networks</h3>
          <p className="font-mono text-xs text-[#555555] mt-2 uppercase tracking-wider font-semibold">fMRI Proxies (14 Regions)</p>
        </div>
        <div className="md:col-span-8 grid grid-cols-1 sm:grid-cols-2 gap-6">
          <div className="p-5 border border-[#E5E5E5] rounded-sm bg-white hover:border-[#111111] transition-colors">
            <h4 className="text-base font-semibold mb-2 flex items-center gap-2 text-[#111111]">
              <span className="w-2 h-2 rounded-full bg-[#111111]"></span> Reward Circuit (VTA)
            </h4>
            <p className="text-[#333333] text-xs leading-relaxed font-normal">
              Predicts dopamine release. High activation indicates the content successfully sets up a premise the brain inherently wants to see resolved.
            </p>
          </div>

          <div className="p-5 border border-[#E5E5E5] rounded-sm bg-white hover:border-[#111111] transition-colors">
            <h4 className="text-base font-semibold mb-2 flex items-center gap-2 text-[#111111]">
              <span className="w-2 h-2 rounded-full bg-[#333333]"></span> Mirror Neurons
            </h4>
            <p className="text-[#333333] text-xs leading-relaxed font-normal">
              Measures parasocial resonance and empathy. Fires heavily when viewing authentic human faces or highly emotive body language. Critical for KOL campaign evaluation.
            </p>
          </div>

          <div className="p-5 border border-[#E5E5E5] rounded-sm bg-white hover:border-[#111111] transition-colors">
            <h4 className="text-base font-semibold mb-2 flex items-center gap-2 text-[#111111]">
              <span className="w-2 h-2 rounded-full bg-[#111111]"></span> Amygdala
            </h4>
            <p className="text-[#333333] text-xs leading-relaxed font-normal">
              Tracks physiological arousal, awe, and surprise. Content breaking standard genre conventions provokes immediate reactions, tied directly to comment velocity.
            </p>
          </div>

          <div className="p-5 border border-[#E5E5E5] rounded-sm bg-white hover:border-[#111111] transition-colors">
            <h4 className="text-base font-semibold mb-2 flex items-center gap-2 text-[#111111]">
              <span className="w-2 h-2 rounded-full bg-gray-600"></span> Prefrontal Cortex
            </h4>
            <p className="text-[#333333] text-xs leading-relaxed font-normal">
              Governs self-relevance and the "share decision." Indicates the viewer believes sharing this content enhances their social standing or identity.
            </p>
          </div>
        </div>
      </div>

      {/* Block 3: Platform SLA Matrix */}
      <div className="border-t border-[#E5E5E5] pt-8 grid grid-cols-1 md:grid-cols-12 gap-8">
        <div className="md:col-span-4">
          <h3 className="font-display text-2xl font-bold text-[#111111]">3. Platform Distribution</h3>
          <p className="font-mono text-xs text-[#555555] mt-2 uppercase tracking-wider font-semibold">Short-Form SLA Fit</p>
        </div>
        <div className="md:col-span-8">
          <div className="overflow-x-auto border border-[#E5E5E5] rounded-sm">
            <table className="w-full text-left font-sans text-xs border-collapse">
              <thead className="bg-[#111111] text-white font-mono uppercase">
                <tr>
                  <th className="p-3.5 border-r border-white/10">Platform</th>
                  <th className="p-3.5 border-r border-white/10">Primary Neural Weights</th>
                  <th className="p-3.5">Algorithmic Priority</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E5E5E5]">
                <tr className="bg-white">
                  <td className="p-3.5 font-bold text-sm text-[#111111] border-r border-[#E5E5E5]">
                    TikTok (FYP)
                  </td>
                  <td className="p-3.5 border-r border-[#E5E5E5] text-[#333333] font-normal">
                    High Visual Density + Fast Pattern Interrupts + TikTok Viral Trends & Audio
                  </td>
                  <td className="p-3.5 font-mono text-[#111111]">
                    Share Velocity, Rewatch Rate & Comment Debate
                  </td>
                </tr>

                <tr className="bg-white">
                  <td className="p-3.5 font-bold text-sm text-[#111111] border-r border-[#E5E5E5]">
                    Instagram (Reels)
                  </td>
                  <td className="p-3.5 border-r border-[#E5E5E5] text-[#333333] font-normal">
                    Aesthetic Framing + Relatable Creator Emotion + Trending Audio Match
                  </td>
                  <td className="p-3.5 font-mono text-[#111111]">
                    DM Shares, Story Reshares & Save Rates
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Block 4: Statistical Reliability & Confidence Interval Protocol */}
      <div className="border-t border-[#E5E5E5] pt-8 grid grid-cols-1 md:grid-cols-12 gap-8">
        <div className="md:col-span-4">
          <h3 className="font-display text-2xl font-bold text-[#111111]">4. Multi-Pass Reliability</h3>
          <p className="font-mono text-xs text-[#555555] mt-2 uppercase tracking-wider font-semibold">95% Confidence Interval (CI)</p>
        </div>
        <div className="md:col-span-8 space-y-6">
          <div className="bg-neutral-100 border border-neutral-300 p-6 rounded-sm space-y-3">
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-neutral-900" />
              <h4 className="text-lg font-bold text-neutral-900">Why Repeat Uploads Vary Within ±1.5 - 2.5 Points</h4>
            </div>
            <p className="text-neutral-800 text-sm leading-relaxed font-normal">
              Large Multimodal Vision AI models (Gemini 3.8 Flash / Pro) evaluate high-frame-rate video media through non-deterministic neural attention sampling. Just as human neural responses to identical media exhibit micro-variations, AI visual and auditory feature tokenization produces small point variance when re-analyzing the exact same video file.
            </p>
            <div className="bg-white p-4 rounded-xs border border-neutral-300 font-mono text-xs text-neutral-900 space-y-1.5">
              <div><strong>• Standard Margin of Error:</strong> ±2.0 to ±2.5 points per run</div>
              <div><strong>• 95% Confidence Interval (CI):</strong> Guaranteed statistical bounds [Score - Margin, Score + Margin]</div>
              <div><strong>• Practical Guidance:</strong> If Video A scores 91 (95% CI: 88.8–93.2) on Run 1 and 92.5 on Run 2, both scores are statistically identical and fall comfortably inside the expected confidence interval.</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

